Fixed accuracy in some cases
mobius3/tweeny pull request #42
Opened 2024-04-05 00:33 UTC by sampad1370

Also, it's improved with removing dividing and multiplying with "total"  in every step.

It will be fixed incorrect result in the following example:

``
auto tween = tweeny::from(1.0f, 1.0f)
                     .to(7.0f, 7.0f)
                     .during(60)
                     .via(tweeny::easing::enumerated::linear)
                     .onStep([](float i, float f) {
                         printf("running: i=%f f=%f\n", i, f);
                         fflush(stdout);
                         return false;
                     });
    while (tween.progress() < 1.0f) {
        auto [value1, value2] = tween.peek(tween.progress());
        printf(" progress:%f and values is: %f,%f\n", tween.progress(), value1, value2);
        fflush(stdout);
        tween.step(10);
    }
    fflush(stdout);
    tween.backward();
    while (tween.progress() > 0.0f) {
        auto [value1, value2] = tween.peek(tween.progress());
        printf(" progress:%f and values is: %f,%f\n", tween.progress(), value1, value2);
        fflush(stdout);
        tween.step(10);
    }
    auto [value1, value2] = tween.peek(tween.progress());
    printf(" progress:%f and values is: %f,%f\n", tween.progress(), value1, value2);
``

I get following result on Ubuntu 22.04 with gcc-11 without this commit:

 progress:0.000000 and values is: 1.000000,1.000000
running: i=2.000000 f=2.000000
 progress:0.166667 and values is: 2.000000,2.000000
running: i=3.000000 f=3.000000
 progress:0.333333 and values is: 3.000000,3.000000
running: i=4.000000 f=4.000000
 progress:0.500000 and values is: 4.000000,4.000000
running: i=5.000000 f=5.000000
 progress:0.666667 and values is: 5.000000,5.000000
running: i=6.000000 f=6.000000
 progress:0.833333 and values is: 6.000000,6.000000
running: i=7.000000 f=7.000000
 progress:1.000000 and values is: 7.000000,7.000000
running: i=6.000000 f=6.000000
 progress:0.833333 and values is: 6.000000,6.000000
running: i=4.900000 f=4.900000
 progress:0.666667 and values is: 4.900000,4.900000
running: i=3.900000 f=3.900000
 progress:0.500000 and values is: 3.900000,3.900000
running: i=2.900000 f=2.900000
 progress:0.333333 and values is: 2.900000,2.900000
running: i=1.900000 f=1.900000
 progress:0.166667 and values is: 1.900000,1.900000
running: i=1.000000 f=1.000000
 progress:0.000000 and values is: 1.000000,1.000000

but it must be:

 progress:0.000000 and values is: 1.000000,1.000000
running: i=2.000000 f=2.000000
 progress:0.166667 and values is: 2.000000,2.000000
running: i=3.000000 f=3.000000
 progress:0.333333 and values is: 3.000000,3.000000
running: i=4.000000 f=4.000000
 progress:0.500000 and values is: 4.000000,4.000000
running: i=5.000000 f=5.000000
 progress:0.666667 and values is: 5.000000,5.000000
running: i=6.000000 f=6.000000
 progress:0.833333 and values is: 6.000000,6.000000
running: i=7.000000 f=7.000000
 progress:1.000000 and values is: 7.000000,7.000000
running: i=6.000000 f=6.000000
 progress:0.833333 and values is: 6.000000,6.000000
running: i=5.000000 f=5.000000
 progress:0.666667 and values is: 5.000000,5.000000
running: i=4.000000 f=4.000000
 progress:0.500000 and values is: 4.000000,4.000000
running: i=3.000000 f=3.000000
 progress:0.333333 and values is: 3.000000,3.000000
running: i=2.000000 f=2.000000
 progress:0.166667 and values is: 2.000000,2.000000
running: i=1.000000 f=1.000000
 progress:0.000000 and values is: 1.000000,1.000000

The result of direct stepping and backward stepping is different! And I think there are many similar cases. And I think extra divining and multiplying can be removed.
Please check my commit.

2024-04-12 11:37 UTC, mobius3 requested changes
Thanks! This is very nice and I'm willing to accept it, but there are some unrelated edits, mostly in regards to formatting, that I don't think are justifiable for what this PR does (it's even harder to review because of that). I was going to point it out directly at each inconsistency but I suggest, at least for this PR, turning off code formatting in your IDE, reverting the code to what it was previously and performing your changes again, without breaking code style.

2025-09-09 17:00 UTC, Tomico-DEV commented
Is this PR still active? I could make the changes requested if you add me as a collaborator @sampad1370

2025-09-09 22:09 UTC, sampad1370 commented
@Tomico-DEV Yes, I think, because these commits fix an issue that cause to incorrect values. How do I add you as collaborator?

2025-09-10 05:02 UTC, Tomico-DEV commented
@sampad1370 I think you'd need to add me as a collaborator of the forked repository. See [this guide](https://docs.github.com/en/account-and-profile/how-tos/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository) for details

2025-09-10 05:04 UTC, Tomico-DEV commented
Or maybe I could open a PR on your repo with the changes? Which do you prefer?

2025-09-11 12:31 UTC, sampad1370 commented
@Tomico-DEV Yes, It must be ok and I invited you as collaborator to my forks. Thanks for your kindness.

2025-09-21 10:59 UTC, sampad1370 commented
@mobius3  I revert some breaking code styles as you said, please check again.
thanks

2025-09-22 00:12 UTC, merged

2025-09-22 00:12 UTC, mobius3 commented
Thanks! Code has been merged.